#pragma once
// Native Hylian FFI generator.  This deliberately lives in Zora: generated
// .hyi files are build outputs, not a second hand-maintained binding format.
#include <clang-c/Index.h>
#include <filesystem>
#include <fstream>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace Zora {
namespace fs = std::filesystem;

inline std::string cx(CXString s) { std::string v = clang_getCString(s) ? clang_getCString(s) : ""; clang_disposeString(s); return v; }
inline std::string hy_type(CXType t) {
    std::string s = cx(clang_getTypeSpelling(t));
    while (!s.empty() && s[0] == ' ') s.erase(0, 1);
    if (s == "void") return "void";
    if (s == "float" || s == "double") return "float";
    if (s == "char" || s == "signed char") return "int8";
    if (s == "unsigned char") return "uint8";
    if (s == "short" || s == "signed short") return "int16";
    if (s == "unsigned short") return "uint16";
    if (s == "char *" || s == "const char *") return "str";
    if (s.find('*') != std::string::npos) return "*void";
    if (s == "_Bool" || s == "bool") return "bool";
    if (s.find("unsigned") != std::string::npos) return "uint";
    if (s == "short" || s == "int" || s == "long" || s == "long long") return "int";
    if (s.rfind("struct ", 0) == 0) return s.substr(7);
    return s.empty() ? "*void" : s;
}
struct HyCtx { std::ofstream* out; std::string file; std::set<std::string> seen; };
inline bool from_main(CXCursor c, const std::string& file) {
    CXSourceLocation l = clang_getCursorLocation(c); CXFile f{}; unsigned line, col, off;
    clang_getExpansionLocation(l, &f, &line, &col, &off);
    return f && cx(clang_getFileName(f)) == file;
}
inline CXChildVisitResult emit_cursor(CXCursor c, CXCursor, CXClientData data) {
    auto& x = *static_cast<HyCtx*>(data); if (!from_main(c, x.file)) return CXChildVisit_Continue;
    auto k = clang_getCursorKind(c);
    std::string n = cx(clang_getCursorSpelling(c));
    if (n.empty() && k == CXCursor_EnumDecl) n = "__anonymous_enum";
    if (n.empty() || x.seen.count(n)) return CXChildVisit_Continue;
    if (k == CXCursor_FunctionDecl) {
        std::string ret = hy_type(clang_getResultType(clang_getCursorType(c))); *x.out << "fn " << n << "(";
        int count = clang_Cursor_getNumArguments(c);
        for (int i=0; i<count; ++i) { if (i) *x.out << ", "; CXCursor a = clang_Cursor_getArgument(c, i); std::string an=cx(clang_getCursorSpelling(a)); *x.out << (an.empty()?"arg":an) << ": " << hy_type(clang_getCursorType(a)); }
        *x.out << ")" << (ret != "void" ? " -> " + ret : "") << "\n"; x.seen.insert(n); return CXChildVisit_Continue;
    }
    if (k == CXCursor_EnumDecl) {
        bool any=false; clang_visitChildren(c, [](CXCursor q,CXCursor,CXClientData d){ auto* o=static_cast<std::ofstream*>(d); if (clang_getCursorKind(q)==CXCursor_EnumConstantDecl) { *o << "const " << cx(clang_getCursorSpelling(q)) << " = " << clang_getEnumConstantDeclValue(q) << "\n"; return CXChildVisit_Continue; } return CXChildVisit_Recurse; }, x.out); (void)any; x.seen.insert(n); return CXChildVisit_Continue;
    }
    if (k == CXCursor_StructDecl) {
        *x.out << "struct " << n << " {\n";
        clang_visitChildren(c, [](CXCursor q,CXCursor,CXClientData d){ if (clang_getCursorKind(q)==CXCursor_FieldDecl) *static_cast<std::ofstream*>(d) << "    " << hy_type(clang_getCursorType(q)) << " " << cx(clang_getCursorSpelling(q)) << "\n"; return CXChildVisit_Continue; }, x.out);
        *x.out << "}\n"; x.seen.insert(n); return CXChildVisit_Continue;
    }
    if (k == CXCursor_ClassDecl) { *x.out << "class " << n << " {}\n"; x.seen.insert(n); }
    return CXChildVisit_Continue;
}
inline bool generate_hyi_from_header(const fs::path& header, const std::string& module,
                                     const std::string& pkg, const fs::path& out,
                                     const std::vector<fs::path>& includes) {
    bool cpp = header.extension()==".hpp" || header.extension()==".hh" || header.extension()==".hxx" || header.extension()==".cpp" || header.extension()==".cc" || header.extension()==".cxx";
    std::vector<std::string> args{"-x", cpp ? "c++" : "c", cpp ? "-std=c++17" : "-std=c11"};
    for (auto& i: includes) { args.push_back("-I"); args.push_back(i.string()); }
    std::vector<const char*> av; for (auto& a: args) av.push_back(a.c_str());
    CXIndex idx=clang_createIndex(0,0); CXTranslationUnit tu=nullptr;
    if (clang_parseTranslationUnit2(idx, header.c_str(), av.data(), (int)av.size(), nullptr,0,CXTranslationUnit_DetailedPreprocessingRecord,&tu)!=CXError_Success) { clang_disposeIndex(idx); return false; }
    fs::create_directories(out.parent_path()); std::ofstream f(out); f << "// Generated by Zora using libclang v2\nmodule " << module << "\nlink \"" << pkg << "\"\npkg \"" << pkg << "\"\n\n";
    HyCtx ctx{&f, fs::absolute(header).string(), {}}; clang_visitChildren(clang_getTranslationUnitCursor(tu), emit_cursor, &ctx);
    f.close(); clang_disposeTranslationUnit(tu); clang_disposeIndex(idx); return true;
}
}
